package org.winkhouse.mwinkhouse.models.columns;

public interface ColloquiColumnNames {
	
	String CODCOLLOQUIO 			= "CODCOLLOQUIO";
	String DESCRIZIONE 				= "DESCRIZIONE";
	String CODAGENTEINSERITORE 		= "CODAGENTEINSERITORE";
	String CODIMMOBILEABBINATO 		= "CODIMMOBILEABBINATO";
	String CODTIPOLOGIACOLLOQUIO 	= "CODTIPOLOGIACOLLOQUIO"; 
	String DATAINSERIMENTO 			= "DATAINSERIMENTO";
	String DATACOLLOQUIO 			= "DATACOLLOQUIO";
	String LUOGO 					= "LUOGO";
	String SCADENZIERE 				= "SCADENZIERE"; 
	String COMMENTOAGENZIA 			= "COMMENTOAGENZIA";
	String COMMENTOCLIENTE 			= "COMMENTOCLIENTE";
	String CODPARENT 				= "CODPARENT"; 
	String ICALUID 					= "ICALUID";
	String CODUSERUPDATE 			= "CODUSERUPDATE"; 
	String DATEUPDATE 				= "DATEUPDATE"; 

}
